### ISSUE TITLE
Bring back number parsing, with precision detection

### ISSUE THREAD

**Issue by aseemk** [csquared/node-logfmt#33]
Hi there,

Great work on node-logfmt!

I'm curious if you'd consider bringing back number parsing (issue #3), but solving the precision issue via detection, rather than not parsing numbers at all.

E.g. here's one way to detect:

```
> parseInt('9007199254740992').toString() == '9007199254740992'
true
> parseInt('9007199254740993').toString() == '9007199254740993'
false
```

(`parseFloat` seems the same, but I'm not knowledgeable there.)

This'd be really helpful, because there are many cases where such large numbers aren't a concern. And it'd be great not to lose proper parsing of those cases just for other ones. =)

Thanks for the consideration!

**Comment by csquared** [comment]
I like the idea of detecting it, but might not be sold on this method exactly. Mind working up a PR?
